#Create a list of students
#Use Tab space so text file is formatted for import into MySQL

students = [
"Alexander	Sutherland",
"Max	Mackay",
"Jessica	Peters",
"Frank	Tucker",
"Stephanie	Butler",
"Emily	Glover",
"Donna	Murray",
"Christian	Paterson",
"Peter	Randall",
"Alexandra	Mackenzie",
"Alan	Mackay",
"Luke	Wallace",
"Megan	Parr",
"Fiona	Sharp",
"Gavin	Fisher",
"Brandon	Churchill",
"Lisa	Buckland",
"Amelia	Bower",
"Adrian	Hamilton",
"Alexander	Springer",
"Kylie	White",
"Carl	Carr",
"Irene	Gray",
"Sarah	Taylor",
"Dorothy	May",
"Kevin	Lee",
"Benjamin	Rampling",
"Nicola	Ross",
"Melanie	Lambert",
"Leah	Lewis",
"Olivia	Clarkson",
"Gabrielle	Paige",
"Claire	Rees",
"Robert	Randall",
"Anna	Hill",
"Alexandra	Bond",
"Michelle	Jones",
"Jason	Peters",
"Karen	Wallace",
"Pippa	Hart",
"Bernadette	Young",
"Nicholas	Kerr",
"Jennifer	Clark",
"Alison	Turner",
"Diane	Lyman",
"Faith	Short",
"Harry	Walker",
"Joe	Edmunds",
"Lillian	Mills",
"Maria	Underwood",
"Richard	Cameron",
"Adam	Oliver",
"Kylie	Blake",
"Neil	Lewis",
"Rebecca	Carr",
"William	Peters",
"David	Lawrence",
"Oliver	Welch",
"Karen	Poole",
"Wendy	White",
"Jessica	Hamilton",
"Rebecca	Wallace",
"Maria	Chapman",
"Lucas	Grant",
"Diane	Rutherford",
"Cameron	Dyer",
"Vanessa	Simpson",
"Pippa	MacLeod",
"Claire	King",
"Pippa	Henderson",
"Theresa	Skinner",
"Madeleine	Hill",
"Sophie	Lewis",
"Jacob	Allan",
"Austin	Dyer",
"Gavin	Forsyth",
"Ella	Wallace",
"Carl	Springer",
"Theresa	Jackson",
"Blake	White",
"Natalie	Churchill",
"Donna	Ross",
"Jessica	Thomson",
"Joseph	Kelly",
"Tracey	Miller",
"Simon	Howard",
"Amanda	Cornish",
"Emma	Taylor",
"Carol	Springer",
"Sue	Newman",
"Evan	Walker",
"Evan	Davies",
"Heather	Black",
"Sebastian	Avery",
"Dylan	Hudson",
"Keith	Mackay",
"James	Henderson",
"Jason	Paige",
"Bella	Alsop",
"Neil	Berry",
"Phil	Mitchell",
"Stephanie	Robertson",
"Lauren	Mackay",
"Nicola	Hodges",
"Claire	Mills",
"Max	MacDonald",
"Chloe	Sutherland",
"Sean	Lawrence",
"Carol	Fraser",
"Ryan	Sanderson",
"Fiona	Turner",
"Paul	Ogden",
"Virginia	Ellison",
"Andrew	Roberts",
"Adrian	Simpson",
"Sebastian	Dyer",
"Fiona	North",
"Felicity	Ball",
"Anne	Forsyth",
"Carolyn	Parr",
"Justin	Clark",
"Natalie	Newman",
"Stewart	Gray",
"Brandon	Anderson",
"Colin	Graham",
"Dominic	Reid",
"Sean	Ball",
"Michelle	Jackson",
"Sean	Vaughan",
"Lily	Fisher",
"Jennifer	Ferguson",
"Sean	Welch",
"Gordon	Churchill",
"Cameron	Turner",
"Kevin	Campbell",
"Ian	Walker",
"Abigail	Gray",
"Carolyn	Greene",
"Trevor	Powell",
"Leonard	Arnold",
"Jasmine	Davies",
"Nicola	Randall",
"Sarah	Churchill",
"Lily	Allan",
"Blake	Reid",
"Stephanie	Mackay",
"Alison	Hudson",
"Oliver	Mills",
"Robert	Russell",
"Heather	Gray",
"Brandon	Bower",
"Charles	Mackenzie",
"Lisa	Young",
"Joseph	Ball",
"Adrian	Underwood",
"Trevor	Vance",
"Thomas	Graham",
"Sebastian	Smith",
"Kylie	Roberts",
"Alexander	White",
"Stephen	Hodges",
"Vanessa	Davidson",
"Keith	Nash",
"Samantha	Parr",
"Victoria	Lee",
"James	Knox",
"Cameron	Harris",
"Nicola	Avery",
"Nathan	Langdon",
"Gavin	Ogden",
"Angela	Sutherland",
"Carl	Hunter",
"Andrea	Brown",
"Nicholas	Johnston",
"Kylie	Quinn",
]

#Create function to generate Student IDs
def gen_studentID(first_name, last_name, index):
    #Limit numeric component to 3chars so ID is consistent with MySQL max <=10chars
    return f"{first_name[:3].upper()}{last_name[:1].upper()}{index:03d}"
    #() not necessary in this f-string as grouping not required

#Output data with studentIDs and TAB separation to a text file
output_file = "student_data.txt"
#Use "w" method since we are writing to student_data.txt
with open(output_file, "w") as output_file:
    #create a loop for the list to generate IDs using student info
    for index, student in enumerate(students, start=1):
        #split the concatenated name string in students list
        first_name, last_name = student.split()
        #call gen_studentID function within loop
        student_id = gen_studentID(first_name, last_name, index)
        #output with tabs so MySQL can read the file with tabs
        #Use f string to format the output as intented
        output_file.write(f"{student_id}\t{first_name}\t{last_name}\n")

print(f"Student data has been written to {output_file}")